#!/bin/bash

# Get the current profile from the environment variable
current_profile=$AUTORANDR_CURRENT_PROFILE
echo "Current profile: $current_profile" >> ~/autorandr.log

# Check if the dpis file exists
if [ ! -f ~/.config/autorandr/dpis ]; then
    echo "The dpis file does not exist." >> ~/autorandr.log
    exit 1
fi

# Check if the current profile exists in the dpis file
if ! grep -q $current_profile ~/.config/autorandr/dpis; then
    echo "The current profile does not exist in the dpis file." >> ~/autorandr.log
    exit 1
fi

# Read the dpi associated with the current profile
profile_dpi=$(grep $current_profile ~/.config/autorandr/dpis | cut -d ',' -f 2)

# Get the current dpi using xrdb
current_dpi=$(xrdb -query | grep -i dpi | cut -f 2)
echo "Current dpi: $current_dpi" >> ~/autorandr.log

# Check if the dpi values are different
if [ "$profile_dpi" != "$current_dpi" ]; then
    echo "Setting the new dpi: $profile_dpi" >> ~/autorandr.log

    # Overwrite the .Xresources file with the new dpi
    echo "Xft.dpi: $profile_dpi" > ~/.Xresources

    # Merge the .Xresources file
    xrdb -merge ~/.Xresources

    # Reload i3
    i3-msg restart
fi

